export const products = [
  [
    {
      image: require('../assets/products/bliss.png'),
      name: 'Шоколадный Блисс',
      description: 'Нежный шоколадный бисквит с кремом из темного шоколада.',
      price: 35,
      count: 1,
    },
    {
      image: require('../assets/products/vanil.png'),
      name: 'Ванильное Облако',
      description: 'Легкий ванильный бисквит с крем-чизом и ягодами.',
      price: 40,
      count: 1,
    },
    {
      image: require('../assets/products/karamel.png'),
      name: 'Карамельный Рай',
      description: 'Многослойный карамельный торт с ореховыми крошками.',
      price: 45,
      count: 1,
    },
    {
      image: require('../assets/products/fruktoviy.png'),
      name: 'Фруктовый Сад',
      description: 'Светлый бисквит с фруктовым желе и свежими фруктами.',
      price: 45,
      count: 1,
    },
    {
      image: require('../assets/products/tiramisu.png'),
      name: 'Тирамису',
      description: 'Слоеный пирог с ягодами и сливочным кремом.',
      price: 20,
      count: 1,
    },
    {
      image: require('../assets/products/yagodniy.png'),
      name: 'Ягодный Штрудель',
      description:
        'Традиционный итальянский десерт с маскарпоне и кофейным вкусом.',
      price: 15,
      count: 1,
    },
  ],

  [
    {
      image: require('../assets/products/malinovaye.png'),
      name: 'Малиновое',
      description: 'Ванильный капкейк с малиновым кремом.',
      price: 35,
      count: 1,
    },
    {
      image: require('../assets/products/limonniy.png'),
      name: 'Лимонный Рассвет',
      description: 'Нежный лимонный капкейк с лимонной цедрой.',
      price: 25,
      count: 1,
    },
    {
      image: require('../assets/products/orexoviy.png'),
      name: 'Ореховый Сюрприз',
      description: 'Шоколадный капкейк с ореховой начинкой.',
      price: 25,
      count: 1,
    },
    {
      image: require('../assets/products/vanilniy.png'),
      name: 'Ванильный',
      description: 'Простой ванильный капкейк с белым кремом.',
      price: 30,
      count: 1,
    },
    {
      image: require('../assets/products/kofeynoe.png'),
      name: 'Кофейное Утро',
      description: 'Капкейк с кофейным вкусом и шоколадным кремом.',
      price: 40,
      count: 1,
    },
    {
      image: require('../assets/products/karamelnoe.png'),
      name: 'Карамельное Чудо',
      description: 'Капкейк с карамельным вкусом и карамельной начинкой.',
      price: 15,
      count: 1,
    },
  ],

  [
    {
      image: require('../assets/products/shokoladnaya.png'),
      name: 'Шоколадная Страсть',
      description: 'Шоколадные макаруны с нежным кремом.',
      price: 25,
      count: 1,
    },
    {
      image: require('../assets/products/vanilnoye_detstvo.png'),
      name: 'Ванильное детство',
      description: 'Ванильные макаруны с кремовой начинкой.',
      price: 30,
      count: 1,
    },
    {
      image: require('../assets/products/lavandoviy_son.png'),
      name: 'Лавандовый Сон',
      description: 'Макаруны с ароматом лаванды и лимонным кремом.',
      price: 25,
      count: 1,
    },
    {
      image: require('../assets/products/kofeynoe_probujdeniye.png'),
      name: 'Кофейное Пробуждение',
      description: 'Макаруны с кофейным вкусом и шоколадной начинкой.',
      price: 45,
      count: 1,
    },
    {
      image: require('../assets/products/malinoviy_rassvet.png'),
      name: 'Малиновый Рассвет',
      description: 'Малиновые макаруны с кремовой начинкой.',
      price: 30,
      count: 1,
    },
    {
      image: require('../assets/products/karamelniy_vixr.png'),
      name: 'Карамельный Вихрь',
      description: 'Карамельные макаруны с соленой карамелью.',
      price: 25,
      count: 1,
    },
  ],

  [
    {
      image: require('../assets/products/espresso.png'),
      name: 'Эспрессо',
      description: 'Интенсивный и ароматный.',
      price: 5,
      count: 1,
    },
    {
      image: require('../assets/products/latte.png'),
      name: 'Латте Макиато',
      description: 'Мягкий и кремовый, с легким вкусом кофе.',
      price: 20,
      count: 1,
    },
    {
      image: require('../assets/products/amerikano.png'),
      name: 'Американо',
      description: 'Классический, крепкий кофе с водой.',
      price: 5,
      count: 1,
    },
    {
      image: require('../assets/products/mokachino.png'),
      name: 'Мокачино',
      description: 'Шоколадный кофейный напиток с взбитыми сливками.',
      price: 20,
      count: 1,
    },
    {
      image: require('../assets/products/fruktoviy_smuzi.png'),
      name: 'Фруктовый Смузи',
      description: 'Натуральный смузи из сезонных фруктов.',
      price: 15,
      count: 1,
    },
    {
      image: require('../assets/products/kapuchino.png'),
      name: 'Капучино',
      description: 'Пенный и насыщенный, с балансом молока и кофе.',
      price: 10,
      count: 1,
    },
  ],
];

export const allProducts = [
  {
    image: require('../assets/products/bliss.png'),
    name: 'Шоколадный Блисс',
    description: 'Нежный шоколадный бисквит с кремом из темного шоколада.',
    price: 35,
    count: 1,
  },
  {
    image: require('../assets/products/vanil.png'),
    name: 'Ванильное Облако',
    description: 'Легкий ванильный бисквит с крем-чизом и ягодами.',
    price: 40,
    count: 1,
  },
  {
    image: require('../assets/products/karamel.png'),
    name: 'Карамельный Рай',
    description: 'Многослойный карамельный торт с ореховыми крошками.',
    price: 45,
    count: 1,
  },
  {
    image: require('../assets/products/fruktoviy.png'),
    name: 'Фруктовый Сад',
    description: 'Светлый бисквит с фруктовым желе и свежими фруктами.',
    price: 45,
    count: 1,
  },
  {
    image: require('../assets/products/tiramisu.png'),
    name: 'Тирамису',
    description: 'Слоеный пирог с ягодами и сливочным кремом.',
    price: 20,
    count: 1,
  },
  {
    image: require('../assets/products/yagodniy.png'),
    name: 'Ягодный Штрудель',
    description:
      'Традиционный итальянский десерт с маскарпоне и кофейным вкусом.',
    price: 15,
    count: 1,
  },
  {
    image: require('../assets/products/malinovaye.png'),
    name: 'Малиновое',
    description: 'Ванильный капкейк с малиновым кремом.',
    price: 35,
    count: 1,
  },
  {
    image: require('../assets/products/limonniy.png'),
    name: 'Лимонный Рассвет',
    description: 'Нежный лимонный капкейк с лимонной цедрой.',
    price: 25,
    count: 1,
  },
  {
    image: require('../assets/products/orexoviy.png'),
    name: 'Ореховый Сюрприз',
    description: 'Шоколадный капкейк с ореховой начинкой.',
    price: 25,
    count: 1,
  },
  {
    image: require('../assets/products/vanilniy.png'),
    name: 'Ванильный',
    description: 'Простой ванильный капкейк с белым кремом.',
    price: 30,
    count: 1,
  },
  {
    image: require('../assets/products/kofeynoe.png'),
    name: 'Кофейное Утро',
    description: 'Капкейк с кофейным вкусом и шоколадным кремом.',
    price: 40,
    count: 1,
  },
  {
    image: require('../assets/products/karamelnoe.png'),
    name: 'Карамельное Чудо',
    description: 'Капкейк с карамельным вкусом и карамельной начинкой.',
    price: 15,
    count: 1,
  },
  {
    image: require('../assets/products/shokoladnaya.png'),
    name: 'Шоколадная Страсть',
    description: 'Шоколадные макаруны с нежным кремом.',
    price: 25,
    count: 1,
  },
  {
    image: require('../assets/products/vanilnoye_detstvo.png'),
    name: 'Ванильное детство',
    description: 'Ванильные макаруны с кремовой начинкой.',
    price: 30,
    count: 1,
  },
  {
    image: require('../assets/products/lavandoviy_son.png'),
    name: 'Лавандовый Сон',
    description: 'Макаруны с ароматом лаванды и лимонным кремом.',
    price: 25,
    count: 1,
  },
  {
    image: require('../assets/products/kofeynoe_probujdeniye.png'),
    name: 'Кофейное Пробуждение',
    description: 'Макаруны с кофейным вкусом и шоколадной начинкой.',
    price: 45,
    count: 1,
  },
  {
    image: require('../assets/products/malinoviy_rassvet.png'),
    name: 'Малиновый Рассвет',
    description: 'Малиновые макаруны с кремовой начинкой.',
    price: 30,
    count: 1,
  },
  {
    image: require('../assets/products/karamelniy_vixr.png'),
    name: 'Карамельный Вихрь',
    description: 'Карамельные макаруны с соленой карамелью.',
    price: 25,
    count: 1,
  },

  {
    image: require('../assets/products/espresso.png'),
    name: 'Эспрессо',
    description: 'Интенсивный и ароматный.',
    price: 5,
    count: 1,
  },
  {
    image: require('../assets/products/latte.png'),
    name: 'Латте Макиато',
    description: 'Мягкий и кремовый, с легким вкусом кофе.',
    price: 20,
    count: 1,
  },
  {
    image: require('../assets/products/amerikano.png'),
    name: 'Американо',
    description: 'Классический, крепкий кофе с водой.',
    price: 5,
    count: 1,
  },
  {
    image: require('../assets/products/mokachino.png'),
    name: 'Мокачино',
    description: 'Шоколадный кофейный напиток с взбитыми сливками.',
    price: 20,
    count: 1,
  },
  {
    image: require('../assets/products/fruktoviy_smuzi.png'),
    name: 'Фруктовый Смузи',
    description: 'Натуральный смузи из сезонных фруктов.',
    price: 15,
    count: 1,
  },
  {
    image: require('../assets/products/kapuchino.png'),
    name: 'Капучино',
    description: 'Пенный и насыщенный, с балансом молока и кофе.',
    price: 10,
    count: 1,
  },
];
